version: '3'
services:
  auth-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/Cinema_project/auth_service

  user-service:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./user_service:/Cinema_project/user_service
      - ./config.py:/Cinema_project/config.py
      - ./database.py:/Cinema_project/database.py
      - ./database_connection.py:/Cinema_project/database_connection.py

  admin-service:
    build:
      context: .
      dockerfile: ./admin_service/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./admin_service:/Cinema_project/admin_service
      - ./config.py:/Cinema_project/config.py
      - ./database.py:/Cinema_project/database.py
      - ./database_connection.py:/Cinema_project/database_connection.py

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
