version: '3.9'
services:
  auth-service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=auth

  admin-service:
    build:
      context: .
      dockerfile: ./admin_service/Dockerfile
    container_name: admin-service
    ports:
      - "8001:8001"
    environment:
    - FLASK_APP=admin
    depends_on:
      - auth-service

  user-service:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    container_name: user-service
    ports:
      - "8002:8002"
    environment:
    - FLASK_APP=user
    depends_on:
      - auth-service

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - auth-service
  #     - admin-service
  #     - user-service
